Tripuz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('trip/', include('trip.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('user.urls')),
    path('trip/', include('trip.urls')),
)

trip/urls.py
from user import views
from django.urls import path
from . import views


urlpatterns = [
    path('trip_driver/', views.TripDriver.as_view(), name="trip_driver"),
    path('ordertrip/', views.orderTrip, name="ordertrip"),
]

trip/models.py
from django.db import models


from user.models import *
# from mapbox_location_field.models import AddressAutoHiddenField, LocationField  

import geocoder


class Province(models.Model):
    province = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.province

class District(models.Model):
    district = models.CharField(max_length=100, null=True)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)

    def __str__(self):
        return self.district + "(" + self.province.province + ")"

token = "pk.eyJ1Ijoic2NvdGhpcyIsImEiOiJjaWp1Y2ltYmUwMDBicmJrdDQ4ZDBkaGN4In0.sbihZCZJ56-fsFNKHXF8YQ"

class Station(models.Model):
    address = models.TextField(max_length=200, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    

    def save(self, *args, **kwargs):
        g = geocoder.mapbox(self.address, key=token)
        g = g.latlng
        self.lat = g[0]
        self.long = g[1]
        return super(Station, self).save(*args, **kwargs)

    


class Trip(models.Model):
    driver = models.OneToOneField(Driver, blank=True, on_delete=models.CASCADE)
    departure = models.ForeignKey(District, blank=True, related_name="from_where", on_delete=models.CASCADE)
    arrival = models.ForeignKey(District, blank=True, related_name="to_where", on_delete=models.CASCADE)
    bus = models.ForeignKey(Bus, blank=True, on_delete=models.CASCADE)
    datatime = models.DateTimeField(null=True)
    status = models.BooleanField(default=False)
    seats = models.IntegerField(null=True)
    price = models.FloatField(null=True)

    def __str__(self):
        return self.departure.district + " - " + self.arrival.district

class OrderTrip(models.Model):
    trip = models.ForeignKey(Trip, blank=True, on_delete=models.CASCADE)
    passengers_phone = models.CharField(max_length=14, null=True)
    passengers_name = models.CharField(max_length=100, null=True)
    payment = models.BooleanField(default=False)

    def __str__(self):
        return self.passengers_name

trip/forms.py
from django.forms import fields
from user import models
import django


from django.forms.models import ModelForm
from django import forms
from .models import *


class ProvinceForm(ModelForm):
    class Meta:
        model = Province
        fields = "__all__"


class DistrictForm(ModelForm):
    class Meta:
        model = District
        fields = "__all__"

class StationForm(ModelForm):
    class Meta:
        model = Station
        fields = "__all__"


class TripForm(ModelForm):
    class Meta:
        model = Trip
        fields = "__all__"


class OrderTripForm(ModelForm):
    class Meta:
        model = OrderTrip
        fields = "__all__"

trip/views.py
from django.shortcuts import render
from django.views import View
from .forms import *
from django.shortcuts import redirect
from .models import *
from .filters import TripFilter
from django.core.paginator import EmptyPage, Paginator
from django.views.generic.edit import CreateView
from django.utils.translation import gettext_lazy as _
from django.contrib import messages


class TripDriver(View):
    def get(self, request):
        try:
            driver = request.user.driver
        except:
            driver = False
        if driver:
            buses = Bus.objects.filter(driver=driver)
            tripform = TripForm()
            context = {'tripform': tripform, "buses": buses}
            request.title = "Work driver"
            return render(request, 'trip/trip_drivers.html', context)
        return redirect('userprofile')
    def post(self, request):
        tripform = TripForm(data=request.POST)
        try:
            if tripform.is_valid():
                tForm = tripform.save(commit=False)
                tForm.driver = request.user.driver
                tForm.save()
            
                return redirect('userprofile')
        except:
            messages.success(request, "you information incorrect...")
            return redirect('trip_driver')



        context = {'tripform': tripform}
        return render(request, 'trip/trip_drivers.html', context)

def orderTrip(request):

    ordertrip = Trip.objects.all()
    
    tfilter = TripFilter(request.GET, queryset=ordertrip)
    ordertrip = tfilter.qs
    
    mytrip = OrderTripForm()
    if request.method == "POST":
        mytrip = OrderTripForm(request.POST)
        if mytrip.is_valid():
            mytrip.save()

            return redirect('/')

    context = {'ordertrip': ordertrip, 'tfilter': tfilter, 'mytrip': mytrip}
    return render(request, 'trip/ordertrip.html', context)


# --------------------------------------MAP-----------------------------------

class AddressView(CreateView):

    model = Station
    fields = ['address']
    template_name = 'user/home.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['token'] = 'pk.eyJ1IjoidHVuYWhvYmJ5IiwiYSI6ImNra3IwaDNxcTBtbzAycm81dTFpOWhvcjAifQ.8ixXcuSDUuAlDSlazSLMCA'
        context['addresses'] = Station.objects.all()
        return context

trip/templates/trip/ordertrip.html
{% extends 'home.html' %}
{% block content %}

<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}



<html lang="en">
<head>
    <title>Order Trip</title>
<style>
        body {
            background-color: #fdbe33;
        }

        .card {
            border: none;
            border-radius: 10px
        }

        .c-details span {
            font-weight: 300;
            font-size: 13px
        }

        .icon {
            width: 50px;
            height: 50px;
            background-color: #eee;
            border-radius: 15px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 39px
        }

        .badge span {
            background-color: #fffbec;
            width: 60px;
            height: 25px;
            padding-bottom: 3px;
            border-radius: 5px;
            display: flex;
            color: #fed85d;
            justify-content: center;
            align-items: center
        }

        .progress {
            height: 10px;
            border-radius: 10px
        }

        .progress div {
            background-color: #fdbe33
        }

        .text1 {
            font-size: 14px;
            font-weight: 600
        }

        .text2 {
            color: #a5aec0
        }
    </style>
</head>
<body>
    <div class="container mt-5 mb-1">
        <form method="GET">
            {{ tfilter.form | crispy }}
            <button class="btn btn-primary" >{% trans 'Search' %}</button>

        </form>
    </div>
<!---------------------------------------------------------------------------------->
{%for item in ordertrip%}
<div class="feature wow fadeInUp" data-wow-delay="0.2s">
    <div class="container">
        <div class="row align-items-center">
            
            <div class="col-lg-12 col-md-12">
                <div class="feature-item">
                    <div class="feature-icon">
                        <i class="flaticon-worker"></i>
                    </div>
                    <div class="feature-text">
                        <div class="ms-2 c-details">
                            <h3 class="mb-0">{% trans 'Driver:' %} {{item.driver}}</h3><br>
                        </div>
                        <h3 class="heading">{{item.departure}} - {{item.arrival}}</h3>
                        <h3>{% trans 'Departure Time:' %} {{item.datatime}}</h3>
                        <h3>{% trans 'Price:' %} {{item.price}} sum</h3>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: 30%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <div class="mt-3"> <span class="text1">{% trans 'have 32 seats' %} <span class="text2"> of {{item.seats}} seats</span></span> </div> 
                        <button type="button" style="background-color: #fdbe33;" class="btn btn-toolbar" data-toggle="modal" data-target="#modalPush">{% trans 'Submit' %}</button>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
{% endfor %}
<!-- -----------------------------------MODAL---------------------------------- -->
  
<div class="modal fade" id="modalPush" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"aria-hidden="true">
    <div class="modal-dialog modal-notify modal-info" role="document">
      <div class="modal-content text-center">
        <div class="modal-header d-flex justify-content-center">
          
        
        <!-- <div class="modal-body">
          <i class="fas fa-bell fa-4x animated rotateIn mb-4"></i>
          <p>Do you want to receive the push notification about the newest posts?</p>
        </div> -->
        <form method="POST">
            {% csrf_token %}

            {{ mytrip|crispy }}
            <input type="submit" class="btn btn-warning" value="Submit">
        </form>
        <!-- <div class="modal-footer flex-center">
          <a href="" class="btn btn-warning">Yes</a>
          <a type="button" class="btn btn-outline-warning waves-effect" data-dismiss="modal">No</a>
        </div> -->
    </div>
      </div>
    </div>
  </div> 


</body>
</html>



{% endblock %}

trip/templates/trip/trip_drivers.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}

<html lang="en">

<head>

    <title>Trip Drivers</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

       
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
        <!-- Favicon -->
        <link href="{% static 'passengers/img/favicon.ico' %}" rel="icon">
    
        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    
        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'user/lib/flaticon/font/flaticon.css' %}" rel="stylesheet"> 
        <link href="{% static 'user/lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'user/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'user/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">
        <link href="{% static 'user/lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'user/lib/slick/slick-theme.css' %}" rel="stylesheet">
    
        <!-- Template Stylesheet -->
        <link href="{% static 'user/css/style.css' %}" rel="stylesheet" type="text/css">
</head>

<body style="background-color: #fdbe33;">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="{{ message.tags }} alert-dismissble mt-4">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}    
    </div>

    <div class="feature wow fadeInUp" data-wow-delay="0.2s">
        <div class="container">
            <div class="cow align-items-center">
                <div class="col-lg-24 col-md-12">
                    <div class="feature-item">

                        <div class="feature-text" style="color: #fdbe33;">

                            <h1 style="color: #fdbe33;">Create Trip</h1>
                            <form method="POST">
                                {% csrf_token %}

                                {{ tripform.departure | as_crispy_field }}
                                {{ tripform.arrival | as_crispy_field }}
                                <div id="div_id_bus" class="form-group"> <label for="id_bus" class=" requiredField">
                                        Bus<span class="asteriskField">*</span> </label>
                                    <div class=""> <select name="bus" class="select form-control" required="" id="id_bus">
                                            <option value="" selected="">---------</option>
                                            {% for object in buses %}
                                                <option value="{{object.id}}">{{object}}</option>
                                            {% endfor %}
                                        </select> </div>
                                </div>
                                {{ tripform.datatime | as_crispy_field }}
                                {{ tripform.seats | as_crispy_field }}
                                {{ tripform.status | as_crispy_field }}
                                {{ tripform.price | as_crispy_field }}
                                <input type="submit" value="Submit" class="btn btn-warning">
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div> 
    
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'user/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'user/lib/wow/wow.min.js' %}"></script>
<script src="{% static 'user/lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'user/lib/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'user/lib/lightbox/js/lightbox.min.js' %}"></script>
<script src="{% static 'user/lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'user/lib/counterup/counterup.min.js' %}"></script>
<script src="{% static 'user/lib/slick/slick.min.js' %}"></script>
<script src="{% static 'user/js/orderJS.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'user/js/main.js' %}"></script>
</body>

</html>